package ejemplo03.dominio;
// Generated 19-feb-2019 10:12:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cine generated by hbm2java
 */
public class Cine  implements java.io.Serializable {


     private Integer idCine;
     private String nombreCine;
     private String direcionCine;
     private String municipioCine;
     private Set<Sesion> sesions = new HashSet<Sesion>(0);

    public Cine() {
    }

	
    public Cine(String nombreCine, String direcionCine, String municipioCine) {
        this.nombreCine = nombreCine;
        this.direcionCine = direcionCine;
        this.municipioCine = municipioCine;
    }
    public Cine(String nombreCine, String direcionCine, String municipioCine, Set<Sesion> sesions) {
       this.nombreCine = nombreCine;
       this.direcionCine = direcionCine;
       this.municipioCine = municipioCine;
       this.sesions = sesions;
    }
   
    public Integer getIdCine() {
        return this.idCine;
    }
    
    public void setIdCine(Integer idCine) {
        this.idCine = idCine;
    }
    public String getNombreCine() {
        return this.nombreCine;
    }
    
    public void setNombreCine(String nombreCine) {
        this.nombreCine = nombreCine;
    }
    public String getDirecionCine() {
        return this.direcionCine;
    }
    
    public void setDirecionCine(String direcionCine) {
        this.direcionCine = direcionCine;
    }
    public String getMunicipioCine() {
        return this.municipioCine;
    }
    
    public void setMunicipioCine(String municipioCine) {
        this.municipioCine = municipioCine;
    }
    public Set<Sesion> getSesions() {
        return this.sesions;
    }
    
    public void setSesions(Set<Sesion> sesions) {
        this.sesions = sesions;
    }




}


