package ejemplo03.dominio;
// Generated 19-feb-2019 10:12:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private Integer idPelicula;
     private String tituloPelicula;
     private String directorPelicula;
     private String interpretePelicula;
     private String categoriaPelicula;
     private String duracionPelicula;
     private String sinopsisPelicula;
     private Set<Sesion> sesions = new HashSet<Sesion>(0);

    public Pelicula() {
    }

	
    public Pelicula(String tituloPelicula, String directorPelicula, String interpretePelicula, String categoriaPelicula, String duracionPelicula, String sinopsisPelicula) {
        this.tituloPelicula = tituloPelicula;
        this.directorPelicula = directorPelicula;
        this.interpretePelicula = interpretePelicula;
        this.categoriaPelicula = categoriaPelicula;
        this.duracionPelicula = duracionPelicula;
        this.sinopsisPelicula = sinopsisPelicula;
    }
    public Pelicula(String tituloPelicula, String directorPelicula, String interpretePelicula, String categoriaPelicula, String duracionPelicula, String sinopsisPelicula, Set<Sesion> sesions) {
       this.tituloPelicula = tituloPelicula;
       this.directorPelicula = directorPelicula;
       this.interpretePelicula = interpretePelicula;
       this.categoriaPelicula = categoriaPelicula;
       this.duracionPelicula = duracionPelicula;
       this.sinopsisPelicula = sinopsisPelicula;
       this.sesions = sesions;
    }
   
    public Integer getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(Integer idPelicula) {
        this.idPelicula = idPelicula;
    }
    public String getTituloPelicula() {
        return this.tituloPelicula;
    }
    
    public void setTituloPelicula(String tituloPelicula) {
        this.tituloPelicula = tituloPelicula;
    }
    public String getDirectorPelicula() {
        return this.directorPelicula;
    }
    
    public void setDirectorPelicula(String directorPelicula) {
        this.directorPelicula = directorPelicula;
    }
    public String getInterpretePelicula() {
        return this.interpretePelicula;
    }
    
    public void setInterpretePelicula(String interpretePelicula) {
        this.interpretePelicula = interpretePelicula;
    }
    public String getCategoriaPelicula() {
        return this.categoriaPelicula;
    }
    
    public void setCategoriaPelicula(String categoriaPelicula) {
        this.categoriaPelicula = categoriaPelicula;
    }
    public String getDuracionPelicula() {
        return this.duracionPelicula;
    }
    
    public void setDuracionPelicula(String duracionPelicula) {
        this.duracionPelicula = duracionPelicula;
    }
    public String getSinopsisPelicula() {
        return this.sinopsisPelicula;
    }
    
    public void setSinopsisPelicula(String sinopsisPelicula) {
        this.sinopsisPelicula = sinopsisPelicula;
    }
    public Set<Sesion> getSesions() {
        return this.sesions;
    }
    
    public void setSesions(Set<Sesion> sesions) {
        this.sesions = sesions;
    }




}


