package ejemplo03.dominio;
// Generated 19-feb-2019 10:12:49 by Hibernate Tools 4.3.1



/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private Integer idSesion;
     private Cine cine;
     private Pelicula pelicula;
     private String horasSesion;
     private String diaSesion;

    public Sesion() {
    }

    public Sesion(Cine cine, Pelicula pelicula, String horasSesion, String diaSesion) {
       this.cine = cine;
       this.pelicula = pelicula;
       this.horasSesion = horasSesion;
       this.diaSesion = diaSesion;
    }
   
    public Integer getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(Integer idSesion) {
        this.idSesion = idSesion;
    }
    public Cine getCine() {
        return this.cine;
    }
    
    public void setCine(Cine cine) {
        this.cine = cine;
    }
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }
    public String getHorasSesion() {
        return this.horasSesion;
    }
    
    public void setHorasSesion(String horasSesion) {
        this.horasSesion = horasSesion;
    }
    public String getDiaSesion() {
        return this.diaSesion;
    }
    
    public void setDiaSesion(String diaSesion) {
        this.diaSesion = diaSesion;
    }




}


